DROP DATABASE IF EXISTS sistema;
CREATE DATABASE sistema;
USE sistema;
CREATE TABLE funcionario(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	nome_funcionario VARCHAR(255) NOT NULL,
	matricula int NOT NULL,
	endereco VARCHAR(255) NOT NULL,
	cargo VARCHAR(255) NOT NULL,
	telefone VARCHAR(255) NOT NULL
	);
	
	CREATE TABLE cliente(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	nome_cliente VARCHAR(255) NOT NULL,
	endereco VARCHAR(255) NOT NULL,
	telefone VARCHAR(255) NOT NULL,
	cpf VARCHAR(255) NOT NULL
	);
	
	CREATE TABLE automovel(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	modelo VARCHAR(255) NOT NULL,
	placa VARCHAR(255) NOT NULL,
	ano VARCHAR(255) NOT NULL,
	valor VARCHAR(255) NOT NULL
	);
	
	CREATE TABLE aluguel(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	id_funcionario VARCHAR(255) NOT NULL,
	id_cliente VARCHAR(255) NOT NULL,
	id_automovel VARCHAR(255) NOT NULL,
	valor VARCHAR(255) NOT NULL
	);

CREATE TABLE usuario(
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(255) NOT NULL,
	usuario VARCHAR(255) NOT NULL,
	senha VARCHAR(255) NOT NULL
);

INSERT INTO usuario VALUES
	(DEFAULT,'Administrador','admin','123');	